### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "c4a450244163a889a9c7d6a92bff41eff3e41627";
          sha256 = "0pfc28392grf54865rvkh9s1gc7fhv6j10yjxzdmri89s8f4kyl6";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.13.1";
  selection = 
  {
    angstrom = 
    {
      pname = "angstrom";
      version = "0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/angstrom/archive/0.15.0.tar.gz";
        sha256 = "01cjjal8vjsm225v9y0q6ixam8k5f821rcr6yix6i9nzs84aq6gi";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml-syntax-shims ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/angstrom/angstrom.0.15.0";
        hash = "sha256:07ryik3g3hz79hnfdwxdh2jsw3cmbgygjs7mjdw07p927wkd83k9";
      };
    };
    asn1-combinators = 
    {
      pname = "asn1-combinators";
      version = "0.2.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.2.6/asn1-combinators-v0.2.6.tbz";
        sha256 = "148s3clqws2nmzwhvlgy0b3nnvq2xbw1qb3mcc865vv9i06xwah1";
      };
      opamInputs = 
      {
        inherit (selection) zarith ptime ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/asn1-combinators/asn1-combinators.0.2.6";
        hash = "sha256:03s1aska9ws9pnjm3v7f69qcx5gdmjh53ximh5zy9v9vf2sxbdsr";
      };
    };
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/v0.14.3.tar.gz";
        sha256 = "0nmydvlbw124c0qz80fx1rpggpr00ylp2zpnyn26qf1a0pfw0kg3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.14.3";
        hash = "sha256:1v61rsyfwkpla41ga6hsagzjihmn1lg5whg2gwb01w9xhdy95qd2";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base64 = 
    {
      pname = "base64";
      version = "3.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-base64/releases/download/v3.5.0/base64-v3.5.0.tbz";
        sha256 = "19735bvb3k263hzcvdhn4d5lfv2qscc9ib4q85wgxsvq0p0fk7aq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base64/base64.3.5.0";
        hash = "sha256:1xlrmf6920bgsrzycmfp3c6nfylxvfq358cjnjglllh8aiwzsl83";
      };
    };
    bigarray-compat = 
    {
      pname = "bigarray-compat";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/bigarray-compat/releases/download/v1.1.0/bigarray-compat-1.1.0.tbz";
        sha256 = "1m8q6ywik6h0wrdgv8ah2s617y37n1gdj4qvc86yi12winj6ji23";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigarray-compat/bigarray-compat.1.1.0";
        hash = "sha256:1hq7lmh99p720plkbv1faqqz2xz4ff9g49kkpsryg9ws3ld8ry05";
      };
    };
    bigstringaf = 
    {
      pname = "bigstringaf";
      version = "0.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.8.0.tar.gz";
        sha256 = "06w66xnqgv8r92x50b3q6xrymry6fviyj572dw7y76cqdzfph18z";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune conf-pkg-config
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigstringaf/bigstringaf.0.8.0";
        hash = "sha256:0q3v7v83pj1rf7qzqj5silkx0s8sjpkwjzkvnmnqkyp4aljqnlnb";
      };
    };
    biniou = 
    {
      pname = "biniou";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/biniou/releases/download/1.2.1/biniou-1.2.1.tbz";
        sha256 = "0da3m0g0dhl02jfynrbysjh070xk2z6rxcx34xnqx6ljn5l6qm1m";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/biniou/biniou.1.2.1";
        hash = "sha256:1m9s9v4zr7022k6d50482qq7w41fdqp58nkpfhcp8574hg65kh69";
      };
    };
    bos = 
    {
      pname = "bos";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/bos/releases/bos-0.2.1.tbz";
        sha256 = "0dwg7lpaq30rvwc5z1gij36fn9xavvpah1bj8ph9gmhhddw2xmnq";
      };
      opamInputs = 
      {
        inherit (selection) topkg rresult ocamlfind ocamlbuild ocaml logs
        fpath fmt base-unix astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bos/bos.0.2.1";
        hash = "sha256:112gl185kjqmkjk54crcimdnpnzf7g1k35srzpkvc4z79x2j0myd";
      };
    };
    ca-certs = 
    {
      pname = "ca-certs";
      version = "0.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ca-certs/releases/download/v0.2.2/ca-certs-v0.2.2.tbz";
        sha256 = "0ll6cv6k02qg03r54d7gylkfh447v8ng4zrq71vri6ay2b67f7jg";
      };
      opamInputs = 
      {
        inherit (selection) x509 ptime ocaml mirage-crypto logs fpath dune
        bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ca-certs/ca-certs.0.2.2";
        hash = "sha256:0hlk4m8ddq4fbrg0yyzzh0dkmg6xv01173g091b9s4x3gxmrnv74";
      };
      buildInputs = [ (pkgs.ca_root_nss or null) ];
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/cmdliner/releases/cmdliner-1.1.0.tbz";
        sha256 = "1i5k2bdmkd97g0il9cxfd8praqbvblnq5k3irwp2c9g5fkh9vdca";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.1.0";
        hash = "sha256:1wz42ijdnbq49q3raz2yyddvqsg0a62wdhhl2wmmz124ymavqz97";
      };
    };
    cohttp = 
    {
      pname = "cohttp";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v5.0.0/cohttp-5.0.0.tbz";
        sha256 = "01asr99hdfw1qkg8wvnslzb1gxfvjs2n421s3gb5b0w1djwg8vzx";
      };
      opamInputs = 
      {
        inherit (selection) uri-sexp uri stringext sexplib0 re ppx_sexp_conv
        ocaml jsonm dune base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp/cohttp.5.0.0";
        hash = "sha256:1661xmd37n1sj3c495br8cclw5qpq67wpkfj0wsijw1hsxs15vim";
      };
    };
    cohttp-lwt = 
    {
      pname = "cohttp-lwt";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v5.0.0/cohttp-5.0.0.tbz";
        sha256 = "01asr99hdfw1qkg8wvnslzb1gxfvjs2n421s3gb5b0w1djwg8vzx";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv ocaml lwt logs dune
        cohttp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt/cohttp-lwt.5.0.0";
        hash = "sha256:1qdwdlvkjbsm7pnjww9vzx9fmv548v05rlzl8zg4865wxzakhvw7";
      };
    };
    cohttp-lwt-unix = 
    {
      pname = "cohttp-lwt-unix";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v5.0.0/cohttp-5.0.0.tbz";
        sha256 = "01asr99hdfw1qkg8wvnslzb1gxfvjs2n421s3gb5b0w1djwg8vzx";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_conv ocaml magic-mime lwt logs fmt dune
        conduit-lwt-unix conduit-lwt cohttp-lwt cmdliner base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt-unix/cohttp-lwt-unix.5.0.0";
        hash = "sha256:00fkk7krxklcq4pjr3gzw5r5709vjfd801bsln8c76yk7ibhxg99";
      };
    };
    conduit = 
    {
      pname = "conduit";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v5.0.0/conduit-5.0.0.tbz";
        sha256 = "1w6z7nsb20mja9l9v0rsd763d3pp1mkh8f948z37gh3v3k9p5ymp";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib ppx_sexp_conv ocaml logs ipaddr-sexp
        ipaddr dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit/conduit.5.0.0";
        hash = "sha256:008l2vn8hmr8dxl97mn1pdrvk8y25x70ychn3ckp695l01kl2ks5";
      };
    };
    conduit-lwt = 
    {
      pname = "conduit-lwt";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v5.0.0/conduit-5.0.0.tbz";
        sha256 = "1w6z7nsb20mja9l9v0rsd763d3pp1mkh8f948z37gh3v3k9p5ymp";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ppx_sexp_conv ocaml lwt dune conduit
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt/conduit-lwt.5.0.0";
        hash = "sha256:1hwdfsyjkg6n0fg71cviwgcixgv6h2pid9izhxmi2apixmjyzal3";
      };
    };
    conduit-lwt-unix = 
    {
      pname = "conduit-lwt-unix";
      version = "5.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v5.0.0/conduit-5.0.0.tbz";
        sha256 = "1w6z7nsb20mja9l9v0rsd763d3pp1mkh8f948z37gh3v3k9p5ymp";
      };
      opamInputs = 
      {
        inherit (selection) uri ppx_sexp_conv ocaml lwt logs ipaddr-sexp
        ipaddr dune conduit-lwt ca-certs
        base-unix;
        tls = selection.tls or null;
        lwt_ssl = selection.lwt_ssl or null;
        launchd = selection.launchd or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt-unix/conduit-lwt-unix.5.0.0";
        hash = "sha256:09nazbcs9kcx6kd4gfpn2r923lnaj9pkndfqqpf6bp0hp9jnq17y";
      };
    };
    conf-gmp = 
    {
      pname = "conf-gmp";
      version = "4";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp/conf-gmp.4";
        hash = "sha256:1jqny2fh81yfhr0frxr5xfcgf0fmgn8c5nhhy7wkxaqsjcdb4144";
      };
      buildInputs = [ (pkgs.gmp or null) (pkgs.gmp-dev or null)
                       (pkgs.gmp-devel or null) (pkgs.libgmp-dev or null) ];
    };
    conf-gmp-powm-sec = 
    {
      pname = "conf-gmp-powm-sec";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.3";
        hash = "sha256:1q9c4av0ah791sq81yva4ga1mz5380r4260bjh060d3mzci00hd3";
      };
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "2";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.2";
        hash = "sha256:1rli6809glz5g9xwp4wsjidc39za4n58xcpkamy6fymfnqha225n";
      };
      buildInputs = [ (pkgs.pkgconfig) ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz";
        sha256 = "0lxy4xkkkwgs1cj6d9lyzsqi9f6fc9r6cir5imi7yjqrpd86s1by";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.8";
        hash = "sha256:0pzd8irqkkkpfgw8nq9d21z9rj5m3qlzixyb7ybfy4b1fwh3n8bp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
        sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.1";
        hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
      };
    };
    cstruct = 
    {
      pname = "cstruct";
      version = "6.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.1/cstruct-v6.0.1.tbz";
        sha256 = "1vcvgba0bb1a0vk1q2cllqxjacanhr3hxgzab4y4alr70j7vnrsa";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct/cstruct.6.0.1";
        hash = "sha256:1fypp9rzvb53h9g8n7ci1k6irpnc5zgww800p86qr81mdz9a5xa4";
      };
    };
    domain-name = 
    {
      pname = "domain-name";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/domain-name/releases/download/v0.4.0/domain-name-0.4.0.tbz";
        sha256 = "1i8846nw81w0dkd76y0a3jw1sk9734qgw4p8fccj15aqhhi6xh55";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/domain-name/domain-name.0.4.0";
        hash = "sha256:1m9bf04jaqqj67vs6k14q1a46gis95lgzs6vjcfj3cq2j7xj5x0c";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.2/fiber-3.0.2.tbz";
        sha256 = "1svdhdc9qxvwzlq2f27n4h6d83vf77bmkw2gapsfac4nhyl3qpd3";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.0.2";
        hash = "sha256:0nslbvajab4k6pbbgbb6gs82fxv4b177apr1whha99djk3i8b5dm";
      };
    };
    dune-build-info = 
    {
      pname = "dune-build-info";
      version = "3.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.2/fiber-3.0.2.tbz";
        sha256 = "1svdhdc9qxvwzlq2f27n4h6d83vf77bmkw2gapsfac4nhyl3qpd3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-build-info/dune-build-info.3.0.2";
        hash = "sha256:092jsmg0x8dr5ldjg4g2nc0acxd38clknf76ngm8y21hk8gh1vn2";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.0.2/fiber-3.0.2.tbz";
        sha256 = "1svdhdc9qxvwzlq2f27n4h6d83vf77bmkw2gapsfac4nhyl3qpd3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.0.2";
        hash = "sha256:10l63hv1fnr09ig8b5bj78i84lw9w0z38syhmlrlsflh9qasvj4m";
      };
    };
    duration = 
    {
      pname = "duration";
      version = "0.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/duration/releases/download/0.2.0/duration-0.2.0.tbz";
        sha256 = "0sffq704n619ncx3xci31z7mbrayj9w12wpigvzkzxx6lmszn55d";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/duration/duration.0.2.0";
        hash = "sha256:0pk9f1mgbrfn0a026k1219hazsbm9zkzlkmdhn3cm5fn071wwq92";
      };
    };
    easy-format = 
    {
      pname = "easy-format";
      version = "1.3.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/easy-format/releases/download/1.3.2/easy-format-1.3.2.tbz";
        sha256 = "09hrikx310pac2sb6jzaa7k6fmiznnmhdsqij1gawdymhawc4h1l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/easy-format/easy-format.1.3.2";
        hash = "sha256:0rjgw1ygf8khwb7vgl5vnw907m8b5mpkb0bnlqiqz9zfmfb4jd47";
      };
    };
    elastic-apm = 
    {
      pname = "elastic-apm";
      version = "development";
      src = self.directSrc "elastic-apm";
      opamInputs = 
      {
        inherit (selection) yojson ptime ppx_yojson_conv ocaml mtime hex
        dune-configurator dune-build-info dune;
      };
      opamSrc = "elastic-apm.opam";
    };
    elastic-apm-logs-reporter = 
    {
      pname = "elastic-apm-logs-reporter";
      version = "development";
      src = self.directSrc "elastic-apm-logs-reporter";
      opamInputs = 
      {
        inherit (selection) ocaml logs elastic-apm dune;
      };
      opamSrc = "elastic-apm-logs-reporter.opam";
    };
    elastic-apm-lwt-client = 
    {
      pname = "elastic-apm-lwt-client";
      version = "development";
      src = self.directSrc "elastic-apm-lwt-client";
      opamInputs = 
      {
        inherit (selection) ocaml lwt_ppx lwt elastic-apm-lwt-reporter
        elastic-apm dune cohttp-lwt-unix;
      };
      opamSrc = "elastic-apm-lwt-client.opam";
    };
    elastic-apm-lwt-reporter = 
    {
      pname = "elastic-apm-lwt-reporter";
      version = "development";
      src = self.directSrc "elastic-apm-lwt-reporter";
      opamInputs = 
      {
        inherit (selection) ocaml lwt elastic-apm dune cohttp-lwt-unix;
      };
      opamSrc = "elastic-apm-lwt-reporter.opam";
    };
    elastic-apm-rock = 
    {
      pname = "elastic-apm-rock";
      version = "development";
      src = self.directSrc "elastic-apm-rock";
      opamInputs = 
      {
        inherit (selection) rock ocaml lwt_ppx elastic-apm-lwt-client
        dune-build-info dune;
      };
      opamSrc = "elastic-apm-rock.opam";
    };
    eqaf = 
    {
      pname = "eqaf";
      version = "0.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/eqaf/releases/download/v0.8/eqaf-v0.8.tbz";
        sha256 = "0xgq3i3vkv9rzbbrg9f1gs9x6cyjdggqdr027sadfdvl21ha2i8i";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/eqaf/eqaf.0.8";
        hash = "sha256:1riqd7dqgq5cf0y7m0fbpszcpazv1kcj1qii3kd0i9wiha46hd9l";
      };
    };
    faraday = 
    {
      pname = "faraday";
      version = "0.8.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/faraday/archive/0.8.1.tar.gz";
        sha256 = "0yngavdplaaw5lb4ci4v4y5nvlhgan0mg1dlx1b5qdjgr83dk7cf";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/faraday/faraday.0.8.1";
        hash = "sha256:1gk9zcifglbfnkjhndd96xf6bfp5ldmrpvvy3daidfd07l56vr96";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.9.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz";
        sha256 = "0q8j2in2473xh7k4hfgnppv9qy77f2ih89yp6yhpbp92ba021yzi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.9.0";
        hash = "sha256:1czh5i3i4mkf9xfasji3v7n821qmnnandlklh67ali0x87brldny";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    gmap = 
    {
      pname = "gmap";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz";
        sha256 = "073wa0lrb0jj706j87cwzf1a8d1ff14100mnrjs8z3xc4ri9xp84";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/gmap/gmap.0.3.0";
        hash = "sha256:1zibwnms9pyvqqchh5mzd48hq32hrs8qcqbai9jwbydnn805ahq5";
      };
    };
    hex = 
    {
      pname = "hex";
      version = "1.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-hex/releases/download/v1.4.0/hex-v1.4.0.tbz";
        sha256 = "07b9y0lmnflsslkrm6xilkj40n8sf2hjqkyqghnk7sw5l0plkqsp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hex/hex.1.4.0";
        hash = "sha256:18miy6dlzajx135gamwwnmwpl80k9mpykpglkbl0s88spca0y97d";
      };
    };
    hmap = 
    {
      pname = "hmap";
      version = "0.8.1";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/hmap/releases/hmap-0.8.1.tbz";
        sha256 = "10xyjy4ab87z7jnghy0wnla9wrmazgyhdwhr4hdmxxdn28dxn03a";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hmap/hmap.0.8.1";
        hash = "sha256:19yc0fm5c0wzxyrwfy3bcb6yh3hbgwrhhh94ggzjs7di8vv9bkv1";
      };
    };
    httpaf = 
    {
      pname = "httpaf";
      version = "0.7.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/httpaf/archive/0.7.1.tar.gz";
        sha256 = "19baxlf0kmhc5dnpz9962wp41yxj0gsi6893pqqkkc54wbs9fbpa";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml faraday dune bigstringaf angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/httpaf/httpaf.0.7.1";
        hash = "sha256:0nspp565d3xylf27vmzxq8015yq26pi6xjhw1zal607qbg29b4yl";
      };
    };
    ipaddr = 
    {
      pname = "ipaddr";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml macaddr dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr/ipaddr.5.2.0";
        hash = "sha256:0159nfklpcl6gkg55gimnd0r5bsih2y7f6v8v4h4124n8hchrqm0";
      };
    };
    ipaddr-sexp = 
    {
      pname = "ipaddr-sexp";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppx_sexp_conv ocaml ipaddr dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr-sexp/ipaddr-sexp.5.2.0";
        hash = "sha256:1k2vf49xna4l7pfgr58mcipypq2qdzfpmcrl02zb2wv58106lvg3";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/jane-street-headers-v0.14.0.tar.gz";
        sha256 = "028yxb4h3iy025iy89v8653m5brh7flrjshghs4x99pd690pmfs7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.14.0";
        hash = "sha256:1w6zjjmyszk9pax139rkxb3vx0w23w0pfd46bddfyfkxq2rbwsvf";
      };
    };
    jsonm = 
    {
      pname = "jsonm";
      version = "1.0.1";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/jsonm/releases/jsonm-1.0.1.tbz";
        sha256 = "1176dcmxb11fnw49b7yysvkjh0kpzx4s48lmdn5psq9vshp5c29w";
      };
      opamInputs = 
      {
        inherit (selection) uutf uchar topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jsonm/jsonm.1.0.1";
        hash = "sha256:0dj8ibg6j4r4a7v7g6d6q3h4m23jv3pxwc7nam4zzbc7h2k69dy9";
      };
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/jst-config/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "0wdjs0lvc5wbggh27cf490jarfibrrb5xxsrigg41m32kjkbijm4";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppx_assert ocaml dune-configurator dune
        base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.14.1";
        hash = "sha256:0myym84b9yx4vqa0ml0zf3cx6rms3g5dv704vhf5bpr7jnqz0qcb";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:0pys6d25bghrwvwd4gflib2yyp5fvdy0rkivbdyli5dmp5j35a3n";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.5.0.tar.gz";
        sha256 = "15gr6nhhfjyh91v9chvm6j7vnp1hhc60y3plgvcgl5yl5k7xbbj9";
      };
      opamInputs = 
      {
        inherit (selection) seq result ocplib-endian ocaml mmap
        dune-configurator dune
        cppo;
        ocaml-syntax-shims = selection.ocaml-syntax-shims or null;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.5.0";
        hash = "sha256:0iadlycd4q93lsk07k9zaimlysgd38sj6v50dc3cb491vl0icipz";
      };
    };
    lwt_ppx = 
    {
      pname = "lwt_ppx";
      version = "2.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.5.0.tar.gz";
        sha256 = "15gr6nhhfjyh91v9chvm6j7vnp1hhc60y3plgvcgl5yl5k7xbbj9";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml lwt dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ppx/lwt_ppx.2.0.3";
        hash = "sha256:11q418mj2zp6dd0wf296j1yf5rxf8hz9ggscdsg112icsgk2z32p";
      };
    };
    macaddr = 
    {
      pname = "macaddr";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr/macaddr.5.2.0";
        hash = "sha256:1w7hg0i037a8f1rggr39m0679qhnp4xzd4ikxvy6573nf3myl2b1";
      };
    };
    magic-mime = 
    {
      pname = "magic-mime";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.2.0/magic-mime-v1.2.0.tbz";
        sha256 = "1xcl0si6zgczfx1788y0qm5wir15fcfd1mczzki9gpgq01svc8gi";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/magic-mime/magic-mime.1.2.0";
        hash = "sha256:0cd3l2cjh2rlvp1r9l5fb0jxhn5176qjw042py9xq999zp09kp21";
      };
    };
    mirage-crypto = 
    {
      pname = "mirage-crypto";
      version = "0.10.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.5/mirage-crypto-v0.10.5.tbz";
        sha256 = "15d49bjb9jv1jfh3ifdqpn4qz2vs9gzd1z5vb3rj81kb2r4qrqkr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml eqaf dune-configurator dune cstruct
        conf-pkg-config;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto/mirage-crypto.0.10.5";
        hash = "sha256:1zpjzk5sb8abj8637kq7rfv7bysal58g803wid2mwvqdgnlwgl1j";
      };
    };
    mirage-crypto-ec = 
    {
      pname = "mirage-crypto-ec";
      version = "0.10.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.5/mirage-crypto-v0.10.5.tbz";
        sha256 = "15d49bjb9jv1jfh3ifdqpn4qz2vs9gzd1z5vb3rj81kb2r4qrqkr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto-rng mirage-crypto eqaf
        dune-configurator dune cstruct
        conf-pkg-config;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-ec/mirage-crypto-ec.0.10.5";
        hash = "sha256:07l9yk2napvsfr6n9p5pvfc2kchcph1641irnds84l2wi6c7qkzz";
      };
    };
    mirage-crypto-pk = 
    {
      pname = "mirage-crypto-pk";
      version = "0.10.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.5/mirage-crypto-v0.10.5.tbz";
        sha256 = "15d49bjb9jv1jfh3ifdqpn4qz2vs9gzd1z5vb3rj81kb2r4qrqkr";
      };
      opamInputs = 
      {
        inherit (selection) zarith sexplib0 ocaml mirage-crypto-rng
        mirage-crypto eqaf dune cstruct
        conf-gmp-powm-sec;
        zarith-freestanding = selection.zarith-freestanding or null;
        mirage-runtime = selection.mirage-runtime or null;
        mirage-no-xen = selection.mirage-no-xen or null;
        mirage-no-solo5 = selection.mirage-no-solo5 or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-pk/mirage-crypto-pk.0.10.5";
        hash = "sha256:15qy98pk9qgzc6p436d8411bisi6n264iyb29js4zz6zwa82iq7i";
      };
    };
    mirage-crypto-rng = 
    {
      pname = "mirage-crypto-rng";
      version = "0.10.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.5/mirage-crypto-v0.10.5.tbz";
        sha256 = "15d49bjb9jv1jfh3ifdqpn4qz2vs9gzd1z5vb3rj81kb2r4qrqkr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mtime mirage-crypto lwt logs duration
        dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.10.5";
        hash = "sha256:1pxz2vlfzvsj42wnwfdy4dg92xdbq3sl47jf5ckx87bas7xypd3m";
      };
    };
    mirage-no-solo5 = 
    {
      pname = "mirage-no-solo5";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-solo5/mirage-no-solo5.1";
        hash = "sha256:18h50v7lp39sis6jy46h35vij0v1z5fr76c4y2h4b72c40fwwck1";
      };
    };
    mirage-no-xen = 
    {
      pname = "mirage-no-xen";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-xen/mirage-no-xen.1";
        hash = "sha256:1nvmvay3nkl8ljw9f46dwv3jppqbbkp0pxf9f1gq4spckb8ysmkh";
      };
    };
    mmap = 
    {
      pname = "mmap";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mmap/releases/download/v1.1.0/mmap-v1.1.0.tbz";
        sha256 = "0l6waidal2n8mkdn74avbslvc10sf49f5d889n838z03pra5chsc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mmap/mmap.1.1.0";
        hash = "sha256:1snhaf6mixmmb49gcin5wmbz4bfjz406mip4556lids8ajm22ibh";
      };
    };
    mtime = 
    {
      pname = "mtime";
      version = "1.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/mtime/releases/mtime-1.4.0.tbz";
        sha256 = "1xy6lg52n2zynp4p164ym9j0f1b95j5n4bi5y4mbdrry9w99h32m";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mtime/mtime.1.4.0";
        hash = "sha256:128s1c15kvbpgx046m4yi8dvjjj0v852wrvd2ii8z4rqgi56hkcs";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
        sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
      };
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.4";
        hash = "sha256:04wb8ww165lsifn36jcrxw5zs87id5kib6rilq6zh6qhzvij88pf";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.13.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.13.1";
        hash = "sha256:12aajj2hc636jr6wbv4vba8pmjdndbcvnw7q35gj4agxmrjspziw";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.13.1.tar.gz";
        sha256 = "1i7ad8lh5l74wb3yzmhlv529wc75a5sjybzkad7wdl8zrj47jk0r";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.13.1";
        hash = "sha256:069i5vsndd9lsvdm5wk898nfnc85ww7459nibjg6881ww43w8ck1";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.1.tar.gz";
        sha256 = "0ml2y3dqhhbwlf94l3jgz6gfhhfp41qaf1sjm8p8c37q1vzpj4jf";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.1";
        hash = "sha256:04ws6wbbsv56r4b6f29514inn77d91gb6sa8z62bxkswk1s1r1fn";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.3";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.3.tar.gz";
        sha256 = "0hfcwamcvinmww59b5i4yxbf0kxyzkp5qv3d1c7ybn9q52vgq463";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.3";
        hash = "sha256:1wq1lkw3rpgilprlakznsxxf60mcidn3fzi3vjrgjdrnnp9hvh19";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz";
        sha256 = "085kskr0cxcnv2d62n3jq1r273p7giisy56zfl26mm7amvl79blp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.2";
        hash = "sha256:1jldvb471gyhkrzwfvqg722l3a8dc37hhhyas66skjzfmqyi2pnh";
      };
    };
    octavius = 
    {
      pname = "octavius";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/octavius/archive/v1.2.2.tar.gz";
        sha256 = "1bg0fcm7haqxvx5wx2cci0mbbq0gf1vw9fa4kkd6jsriw1611jga";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/octavius/octavius.1.2.2";
        hash = "sha256:0bagilkanfjyi56hrk9dw43xs6zry9p8n3l55r3d58v5hz2xsbwl";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/parsexp/archive/refs/tags/v0.14.2.tar.gz";
        sha256 = "0c7jl6sqfawqpvbhci8vyyhgvcyd3lw5lj3jcf5f1p6w1177xqgn";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.14.2";
        hash = "sha256:1fqnxdr1pgxmada77hkhyyr7yybpv2f810shnhvhkpw15h58azx1";
      };
    };
    pbkdf = 
    {
      pname = "pbkdf";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/abeaumont/ocaml-pbkdf/archive/1.2.0.tar.gz";
        sha256 = "0mvlh5iq4wqdfylxaq64sycxihp5jkjdgrrr9wmrlgk2yrsn3d3v";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pbkdf/pbkdf.1.2.0";
        hash = "sha256:0p1yzfcxk2rswqcbvcwgfl7x8ha55pk8dlx0pibjzjzakpxdhrx9";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_assert-v0.14.0.tar.gz";
        sha256 = "1l2rr4jz2q5b35ryn2z146z7m9v6k8krp5gpn8ilib66mnz5zx15";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.14.0";
        hash = "sha256:1ry1bqssjw5lc7h0x2cc7f8rmz807j5l7029lxd4i12vgq91x5km";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_base-v0.14.0.tar.gz";
        sha256 = "0b7a3fmi90jk8paz0g36yzaq670fbnrbi1j8r5ibh9wbcfli7ji6";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_js_style ppx_hash
        ppx_enumerate ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.14.0";
        hash = "sha256:1n66x8xl2n0qbq1g0b1l3nsdqlb3czj5w509riwqdgz11fyrzi25";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_cold-v0.14.0.tar.gz";
        sha256 = "1madfzhpir9amnxmg530n70vll0jrl59vyp71miji73i6b9sy6n2";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.14.0";
        hash = "sha256:0g566vskiblrxr246c3s26rlzxciln518fr4f6d8lid63qgrgnfm";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_compare-v0.14.0.tar.gz";
        sha256 = "0mqxa2s194nif7x4fjn1p5gd9i3bakr8nv27gf8x1g5nmi8q9pmp";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.14.0";
        hash = "sha256:1ndfsgazb7yg5q3aqzcrnr914sf615bsh4z4q202bdvpf0fqj31k";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_enumerate-v0.14.0.tar.gz";
        sha256 = "1ij6sffgqhnjwnj9brhrrw1c6xgxlh0s6r17x1qkgnyrc73gfsz8";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.14.0";
        hash = "sha256:0lgnrpq1vmb44367y7mdr7jw1yqmy08fi6phgq8pch3a47fdk2rm";
      };
    };
    ppx_expect = 
    {
      pname = "ppx_expect";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_expect/archive/v0.14.2.tar.gz";
        sha256 = "1gcjlya6knnsrl60sd3vlgp7arj39xm5fjjfk5sick4z66agm2n5";
      };
      opamInputs = 
      {
        inherit (selection) stdio re ppxlib ppx_inline_test ppx_here ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_expect/ppx_expect.v0.14.2";
        hash = "sha256:14hnawvs9fc87kghg00zj0p1p21f22gdy1767l2nwb4ihl3h133b";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_hash-v0.14.0.tar.gz";
        sha256 = "0x4wgdvhgd8a49bzari52jpkykxpv6ncgp5ncda3xgg0a9r49s8n";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.14.0";
        hash = "sha256:0zcnsd0724w6kpx4w1i3nbfrvffhnqjn3rinddgqjndx5pvghrlc";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_here-v0.14.0.tar.gz";
        sha256 = "0b444djy68v6ji0ypwv5l02pkl151qzrgg96lyhl8dxfrzvj1zkj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.14.0";
        hash = "sha256:0f7p619ymqm27iclcx3cbyyn1k0mccw9vsa0l88m1jk3kjgjbmzz";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_inline_test/archive/v0.14.1.tar.gz";
        sha256 = "0qzvm8rg07annl8zpqlhzx1z8ahrrf02r1brd43ykqas5sww3rfp";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.14.1";
        hash = "sha256:1vwg8bgw093ia075n7vh0kl82sjd5r9yk27s45ljzz9cmfqrr4sa";
      };
    };
    ppx_js_style = 
    {
      pname = "ppx_js_style";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_js_style/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "1nq4rj659f34dc28pj7ir2szqbpky4nzs9qfw0am6sf36jwispiw";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib octavius ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_js_style/ppx_js_style.v0.14.1";
        hash = "sha256:05bc07ghvfd4d85inf1qvpqxphvcg7mgf8fn9ycib6fdmxdkkamq";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_optcomp/archive/v0.14.3.tar.gz";
        sha256 = "0bxzh0pm3zdiadrd37jjzp7zm2qn28mx25ahk0shgfb73vya809n";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.14.3";
        hash = "sha256:0xh7m3hsm7vrhzmd86n3irhydp9lyr23ax9mg1khq2jhcbyqqvy0";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.3.tar.gz";
        sha256 = "0fbnkhsd6yphc49pa21nlmbik99n7qkaz8l9paq96v012ipg9h9g";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.3";
        hash = "sha256:03c4ar76g1sz2y35a9jbffw957i17ixwd7ky8cg5ss7m7jl7x1fs";
      };
    };
    ppx_yojson_conv = 
    {
      pname = "ppx_yojson_conv";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_yojson_conv-v0.14.0.tar.gz";
        sha256 = "0ls6vzj7k0wrjliifqczs78anbc8b88as5w7a3wixfcs1gjfsp2w";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_yojson_conv_lib ppx_js_style ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv/ppx_yojson_conv.v0.14.0";
        hash = "sha256:08awq9hgbbxvr9321m24jxlm3zixwxk9pbk8xv5asglx01dr5ydl";
      };
    };
    ppx_yojson_conv_lib = 
    {
      pname = "ppx_yojson_conv_lib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_yojson_conv_lib-v0.14.0.tar.gz";
        sha256 = "1f1530pvyg05zwi83iwrk3v207w316wlljikwyl9ahjh24lsja46";
      };
      opamInputs = 
      {
        inherit (selection) yojson ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_yojson_conv_lib/ppx_yojson_conv_lib.v0.14.0";
        hash = "sha256:0zg2d8aiflyjs2pcvg509c47gg6d64rk010pflszp19dw9zp1hha";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.24.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.24.0/ppxlib-0.24.0.tbz";
        sha256 = "1j4hg8gc8mkw64gvjghig1179ih90yki54hf8qxmn3yd5ry04rkp";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.24.0";
        hash = "sha256:0yjsgdkfkbwyjj3yihrqnxlpagrbcr1gln7bxfmx96y3xa4fs8jv";
      };
    };
    ptime = 
    {
      pname = "ptime";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/ptime/releases/ptime-1.0.0.tbz";
        sha256 = "02qiwafysw5vpbxmkhgf6hfr5fv967rxzfkfy18kgj3206686724";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ptime/ptime.1.0.0";
        hash = "sha256:0ad40dpgfszf9bibdqygd4f16gbf3b1irx6x7p92cbd6kffmjmrs";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.10.3/re-1.10.3.tbz";
        sha256 = "1fqfg609996bgxr14yyfxhvl6hm9c1j0mm2xjdjigqrzgyb4crc4";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.10.3";
        hash = "sha256:1f2xgscc07g800ia8z43i1p377dj2fjdrpzsqgzvw1dnplwnklya";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    rock = 
    {
      pname = "rock";
      version = "0.20.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/opium/releases/download/0.20.0/opium-0.20.0.tbz";
        sha256 = "1digzxcln1gi2cy4ph3kwm9djf9yy8plnzcbbx9sy2z9dn392srj";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml lwt httpaf hmap dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rock/rock.0.20.0";
        hash = "sha256:0qz2bk7np6vvdpn99v3gqmsfd15xqdpvqf6ggwn2hml3403mwrxi";
      };
    };
    rresult = 
    {
      pname = "rresult";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz";
        sha256 = "0h2mjyzhay1p4k7n0mzaa7hlc7875kiy6m1i3r1n03j6hddpzahi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rresult/rresult.0.7.0";
        hash = "sha256:0131az6qj1086hi1kjc7x99x1q4c0z3axjwd1wbmr6c6r6nnaj6y";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib-v0.14.0.tar.gz";
        sha256 = "12rlnc6fcrjfdn3gs2agi418sj54ighhs6dfll37zcv7mgywblm2";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.14.0";
        hash = "sha256:1nlzjkx60d4z09b15nq35ivzl6akk3svq7nl4vv5swhsmj8gvpl4";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.14.0";
        hash = "sha256:0k9vkjbiibja48c0yayal7xwyik3h3c3v4dwd3j7jbmras63ig2c";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/stdio-v0.14.0.tar.gz";
        sha256 = "1hj5hraprqy2i90a690l11yjszvb99j818q3d684ryx6p2lddk0l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.14.0";
        hash = "sha256:19hlf6bgx1avq4ifwji2rj2f2j26v3nf8ywjnwh2m3dpvfqc4pvk";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    stringext = 
    {
      pname = "stringext";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stringext/stringext.1.6.0";
        hash = "sha256:1yjysjb40yjhqmcx3z12y2nmr2qy215qdnvdns1hxip0fjcd4zkz";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/time_now-v0.14.0.tar.gz";
        sha256 = "0hkn2jw4dz5gflnsblskl5wp6z7zbrahwjmaxmsskfviwjg82cqh";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.14.0";
        hash = "sha256:1s8bqbks0cjw4x68nn5xlkykn3bcqh2rmrx6hgs53dalkiqv7ry0";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.5.tbz";
        sha256 = "1iyinmcfqpprk7k4cc51nqgypayprbj4larwcfqw86k5dri84825";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.5";
        hash = "sha256:04vg4zic7f6zk44vkvqw2fcr562hl7d0gklv3vgphk4n3bnqbcyy";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    uri = 
    {
      pname = "uri";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.2.0/uri-v4.2.0.tbz";
        sha256 = "0szifda6yism5vn5jdizkha3ad0xk6zw4xgfl8g77dnv83ci7h65";
      };
      opamInputs = 
      {
        inherit (selection) stringext ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri/uri.4.2.0";
        hash = "sha256:1s0rbjixhl1ypxv9xxmldlmxm6gj9rrzmcgydp8dna4n0wza4hbf";
      };
    };
    uri-sexp = 
    {
      pname = "uri-sexp";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.2.0/uri-v4.2.0.tbz";
        sha256 = "0szifda6yism5vn5jdizkha3ad0xk6zw4xgfl8g77dnv83ci7h65";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri-sexp/uri-sexp.4.2.0";
        hash = "sha256:0n2g1p9hn7n38pdxyyjahbaa5z37nw1jw1mxgpad7jy86slfilac";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    x509 = 
    {
      pname = "x509";
      version = "0.16.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-x509/releases/download/v0.16.0/x509-0.16.0.tbz";
        sha256 = "159mhfwsiv08sj0zk7s3k813f0mc9vpziwpf6j9r32y3nizp59k7";
      };
      opamInputs = 
      {
        inherit (selection) ptime pbkdf ocaml mirage-crypto-rng
        mirage-crypto-pk mirage-crypto-ec mirage-crypto logs ipaddr gmap fmt
        dune domain-name cstruct base64 asn1-combinators;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/x509/x509.0.16.0";
        hash = "sha256:0a9xcwffyg1di2w1m29bx7b64b98zbv5n9rqzbym6a3510ykk0mx";
      };
    };
    yojson = 
    {
      pname = "yojson";
      version = "1.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/yojson/releases/download/1.7.0/yojson-1.7.0.tbz";
        sha256 = "1iich6323npvvs8r50lkr4pxxqm9mf6w67cnid7jg1j1g5gwcvv5";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune cppo biniou;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yojson/yojson.1.7.0";
        hash = "sha256:1n8iih0jmaf9b0hsv6ph729jajws9w43kgm24324p4wlj45rjs2q";
      };
    };
    zarith = 
    {
      pname = "zarith";
      version = "1.12";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/Zarith/archive/release-1.12.tar.gz";
        sha256 = "1098xpqsq3gwpz9k2gc6ahiz2zk0z0xxi1lwc07nvj2570y5ccnc";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zarith/zarith.1.12";
        hash = "sha256:03by05004bgfkfllpacf3vk1h8i6q7wzwi7cgxy0nyj5ffga0ggh";
      };
    };
  };
}

